-- 코드를 작성해주세요
WITH CHILD AS(
SELECT PARENT_ID, COUNT(*) AS CHILD_COUNT
FROM ECOLI_DATA 
GROUP BY PARENT_ID)

SELECT ID, 
    CASE
    WHEN CHILD_COUNT IS NULL THEN 0
    ELSE CHILD_COUNT
    END AS CHILD_COUNT
FROM ECOLI_DATA E LEFT JOIN CHILD C ON E.ID = C.PARENT_ID
ORDER BY ID