-- 코드를 입력하세요
WITH BEST AS(
SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORITES
FROM REST_INFO 
GROUP BY FOOD_TYPE)

SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, R.FAVORITES
FROM REST_INFO R JOIN BEST B ON R.FOOD_TYPE = B.FOOD_TYPE
WHERE R.FAVORITES = B.MAX_FAVORITES
ORDER BY R.FOOD_TYPE DESC


