-- 코드를 작성해주세요
WITH A AS(
    SELECT N.FISH_TYPE, COUNT(*) AS FISH_COUNT
    FROM FISH_INFO I, FISH_NAME_INFO N
    WHERE I.FISH_TYPE = N.FISH_TYPE
    GROUP BY(N.FISH_TYPE)
)

SELECT FISH_COUNT, FISH_NAME
FROM FISH_NAME_INFO N RIGHT JOIN A a
ON N.FISH_TYPE = a.FISH_TYPE
ORDER BY FISH_COUNT DESC