-- 코드를 입력하세요
WITH A AS (
SELECT YEAR(sales_date) AS YEAR, MONTH(sales_date) AS MONTH, 
    COUNT(DISTINCT(U.USER_ID)) AS PUCHASED_USERS
FROM USER_INFO U JOIN ONLINE_SALE O ON U.USER_ID = O.USER_ID
WHERE JOINED LIKE '2021-%'
GROUP BY YEAR(sales_date), MONTH(sales_date))

#SELECT * FROM A

SELECT *, ROUND(PUCHASED_USERS / 
    (SELECT COUNT(*)
    FROM USER_INFO
    WHERE JOINED LIKE '2021-%'),1) AS PUCHASED_RATIO
FROM A
ORDER BY YEAR, MONTH;


# 2021에 가입한 사람 158명