-- 코드를 입력하세요
WITH RESULT AS(
SELECT CAR_ID, 
    CASE
    WHEN DATEDIFF('2022-10-16',START_DATE) >= 0 AND DATEDIFF(END_DATE, '2022-10-16') >= 0
    THEN 1
    ELSE 0
    END AS NUM
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY)

SELECT CAR_ID, 
    CASE SUM(NUM)
    WHEN 1 THEN '대여중'
    WHEN 0 THEN '대여 가능'
    END AS AVAILABILITY 
FROM RESULT
GROUP BY CAR_ID
ORDER BY CAR_ID DESC