-- 코드를 입력하세요
WITH SALE AS
(
SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD
WHERE STATUS = 'DONE'
GROUP BY WRITER_ID
HAVING TOTAL_SALES >= 700000
)

SELECT U.USER_ID, U.NICKNAME, S.TOTAL_SALES
FROM USED_GOODS_USER U JOIN SALE S ON U.USER_ID = S.WRITER_ID
ORDER BY S.TOTAL_SALES

# SELECT *
# FROM USED_GOODS_BOARD
# WHERE STATUS = 'DONE'
# ORDER BY WRITER_ID
