WITH SELECT_RARE AS (
SELECT I.ITEM_ID AS ITEM_ID
FROM ITEM_INFO I JOIN ITEM_TREE T
ON I.ITEM_ID = T.ITEM_ID
WHERE RARITY = 'RARE')

SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO 
WHERE ITEM_ID IN (
SELECT ITEM_ID
FROM ITEM_TREE
WHERE PARENT_ITEM_ID IN (SELECT * FROM SELECT_RARE ))
ORDER BY ITEM_ID DESC

