-- 코드를 작성해주세요
WITH DIFF AS
(SELECT YEAR(DIFFERENTIATION_DATE) AS Y, MAX(SIZE_OF_COLONY) AS M
FROM ECOLI_DATA
GROUP BY YEAR(DIFFERENTIATION_DATE))

SELECT Y AS YEAR, (M-SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM ECOLI_DATA E JOIN DIFF D ON YEAR(DIFFERENTIATION_DATE) = D.Y
ORDER BY YEAR, YEAR_DEV