-- 코드를 작성해주세요
WITH SUMSCORE AS (
SELECT EMP_NO, SUM(SCORE) AS SCORE
FROM HR_GRADE
WHERE YEAR = '2022'
GROUP BY EMP_NO)

SELECT SCORE, H.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES H , SUMSCORE S
WHERE H.EMP_NO = S.EMP_NO
AND S.SCORE = (SELECT MAX(SCORE)
              FROM SUMSCORE)
      
               
