-- 코드를 작성해주세요
WITH OVER33 AS(
SELECT AVG(IFNULL(LENGTH, 10)) AS LEN, FISH_TYPE
FROM FISH_INFO
GROUP BY FISH_TYPE
HAVING LEN >= 33)

SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM FISH_INFO
WHERE FISH_TYPE IN (SELECT FISH_TYPE FROM OVER33)
GROUP BY FISH_TYPE
ORDER BY FISH_TYPE
